[package]
name = "obsidian-uri-opener-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
open = "5.0.0"
urlencoding = "2.1.2"
